### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by Zhang-Haipeng** [UBC-MDS/pyntrinio#18]
I would suggest setting the type of the `date` in the inputs as `str` type ("%Y-%m-%d", e.g. "2019-12-31"), for user-friendliness.

**Comment by slbsolomon** [comment]
I see benefits to string and datetime objects.
String:
- more human readable
- more prone to errors
- there are different standards geographically for the order of YMD

Datetime object:
- throws an error if you put something invalid in (ie less error messages for us to write)
- less human readable

**Comment by slbsolomon** [comment]
As discussed yesterday, all dates/times will be a string. Updated my docstring in #24
