### ISSUE TITLE
information on companies 

### ISSUE THREAD

**Issue by sirine-chahma** [UBC-MDS/pyntrinio#42]
Does anyone know where we can find all the tickers that we can use, and all the statements (like 'income_statement')?

**Comment by slbsolomon** [comment]
It appears that our limited free access will only give us Sandbox access (which explains what was going on yesterday with @Zhang-Haipeng's access). I will send a PR for the README to explain this shortly.

Companies that are covered in the Developer Sandbox for Fundamentals: https://product.intrinio.com/developer-sandbox/coverage/us-fundamentals-financials-metrics-ratios-stock-prices

All information about the Sandbox: https://product.intrinio.com/developer-sandbox

Statements available: income_statement, balance_sheet_statement, cash_flow_statement
