### ISSUE TITLE
Issue with Indentations for Milestone 2

### ISSUE THREAD

**Issue by slbsolomon** [UBC-MDS/pyntrinio#57]
@yavyx As discussed, I used Rstudio and everyone else used VS Code - in the end everything ran in Rstudio for me, but my groupmates can't run our things - can you only mark me down for this? The Milestone 2 submission won't work by default if you use VS Code

**Comment by Zhang-Haipeng** [comment]
Only marking you down wouldn't be fair @slbsolomon .  It's just part of the teamwork and it's not your fault IMO.  
Thanks for taking a note on this issue. @yavyx

**Comment by aakanksha023** [comment]
Agreed with @Zhang

**Comment by yavyx** [comment]
Noted, you can close this issue
