### ISSUE TITLE
Tasks for Milestone_3

### ISSUE THREAD

**Issue by aakanksha023** [UBC-MDS/pyntrinio#58]
- Assess test(s) coverage for each function
- Communicate the findings to resp. team member(s) by Tuesday night/Wednesday morning

**Comment by aakanksha023** [comment]
Tests to add

> @aakanksha023 : 
- Add test to check API validity (Line 99)
- Write test to check `results` (Last chunk of code till line 153)

Following lines of codes were not executed by the test cases

> @sirine:
- `raise` at line 212
- `raise` at line 223
- `raise` at line 228
- `raise` at line 236
- `except` at line 261-263
- `if-else` line 286-289
- `if-else` lines 320->330

> @slbsolomon 
- `except` at lines 404-408
- `except` at lines 430-432

> @Zhang
- `except` at lines 502-508
- `except` at lines 523-525

**Comment by Zhang-Haipeng** [comment]
I'm confused about why those lines are not executed by the tests. It seems to me that they are executed.   Anybody having/had similar confusion? 
@aakanksha023 @slbsolomon @sirine-chahma 

btw this is me: @Zhang-Haipeng  @aakanksha023

**Comment by slbsolomon** [comment]
@Zhang-Haipeng I am having a similar issue. My lines actually are included in tests. I was thinking it might have something to do with using try-except rather than raise, but it didn't appear so. I planned on going to Tiffany's OH on Friday

**Comment by Zhang-Haipeng** [comment]
@slbsolomon yeah I had similar doubt but they should have been executed in at least the normal case tests (where all the inputs are right).  Maybe we'll need the OH. 

Could anybody share the code to test and show which part is executed or not? I'll need to run some experiments.

**Comment by aakanksha023** [comment]
- Sorry! for the wrong tag @Zhang-Haipeng 
- Same confusion (Though I have not yet spent much time trying to debug this)
- cmd: `poetry run pytest --cov-branch --cov=pyntrinio --cov-report term-missing`

**Comment by slbsolomon** [comment]
Added my full coverage in #66. The issue I was facing was because the name of the functions in the test_ file must begin with test_, ie test_api_error_effective()
