### ISSUE TITLE
Read the Docs issue

### ISSUE THREAD

**Issue by Zhang-Haipeng** [UBC-MDS/pyntrinio#86]
While we followed all the steps, linked our repo to `Read the Docs`, and all the docs rendered just fine locally, it fails to show part of the contents on `Read the Docs`.  (Discussion in the course channel on slack is [here](https://ubc-mds.slack.com/archives/C24GEK3PV/p1584144558441500))
After trying out various methods, we have to leave it as an open issue for now.   
Please kindly note this issue while reviewing, thanks!  @yavyx

**Comment by yavyx** [comment]
Noted!
